name: triple
description: abstraction for the Segmented State Pattern
version: 0.0.26
homepage: https://github.com/Flutterando/triple_pattern

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.2.4
  async: ^2.4.2
  dartz: ^0.9.2

dev_dependencies:
  test: ^1.15.7
