name: mobx_triple
description: Segmented State Pattern for MobX
version: 0.0.25
homepage: https://github.com/Flutterando/triple_pattern

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  mobx: ^1.2.1+4
  meta: ^1.2.4
  triple: 
    path: ../../triple

dev_dependencies:
  test: ^1.15.7



# dependency_overrides:
#   triple: 
#     path: ../triple

